meta_product_name: "The Giving Loop"
meta_title: "The Giving Loop - Closing the Loop on charitable donations"
meta_description: "Relevant description"
meta_image: "THE_GIVING_LOOP.png" # should exist in `app/assets/images/`
